С практик: rethrow; исключения, вылетающие из `new[]` и вектора в целом (возможно, считаем, что на практике?), опционально `std::uninitialized_copy`/`std::uninitialized_move`.
Explicitly excluded: перегрузка `operator new`
exception_ptr?

19-200211, в том числе next/missed

RAII
Исключения из конструкторов, конструкторов полей, delegated, конструкторов базового класса
function try block

сложность с pop() и строгой гарантией в интерфейсе

# Исключения
У нас есть функция.
У неё есть предусловие и постусловие.
Функция завершилась успешно - выполнено постусловие.
Вылетело исключение - постусловие выполнить не удалось.

Конструктор, постусловие: объект успешно создан.
Деструктор, предусловие: объект успешно создан.
Деструктор, постусловие: объект успешно удалён. Это не может сфейлиться.
